%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "any"
    EXTERNAL_NET: "any"
    HTTP_SERVERS: "$HOME_NET"
  port-groups:
    HTTP_PORTS: "any"

default-rule-path: /etc/suricata/rules
rule-files:
  - http-pass-through.rules
  - suricata.rules

classification-file: /etc/suricata/rules/classification.config

pcap-file:
  checksum-checks: no

stream:
  reassembly:
    depth: 0
  midstream: true
  inline: yes

nfq:
  interface: lo
  mode: accept
  checksum-checks: no
  defrag: no

app-layer:
  protocols:
    tls:
      enabled: yes
      detection-ports:
        dp: 443
      encryption-handling: full
    http:
      enabled: yes
      detection-only: no
      ports: "$HTTP_PORTS"
      request-body-limit: 0
      response-body-limit: 0
    libhtp:
      default-config:
        personality: IDS
        request-body-limit: 0
        response-body-limit: 0

outputs:
  - eve-log:
      enabled: yes
      filetype: unix_stream
      filename: /etc/suricata/socket/eve.sock
      types:
        - packet:
            include-payload: yes
            include-payload-printable: yes
        - alert:
            payload-printable: yes
            payload-length: yes
            http-body-printable: yes
            flow: true
            metadata:
              app-layer: true
        - http:
            extended: yes
            dump-all-headers: both

logging:
  default-log-level: debug
  outputs:
    - console:
        enabled: yes
    - file:
        enabled: yes
        level: debug
        filename: /var/log/suricata/suricata.log
