services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    volumes:
      - ./suricata/entrypoint.sh:/etc/suricata/entrypoint.sh
      - ./suricata/logs:/var/log/suricata
      - ./suricata/config:/etc/suricata/config
      - ./suricata/rules:/etc/suricata/rules
      - ./suricata/socket:/etc/suricata/socket
    entrypoint: /etc/suricata/entrypoint.sh
